# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 383cc2e08f615eecf918b9ee38a60c9befc79004845e1da82ed97f078f283dcf3e1bdc0f151a4cc1806be0744f0fa563f16f9eaa8f4856ff8879652c71511e24

test:
  secret_key_base: 296af8f11b95fe4fbf2b26459c45563c1d661784b249bbc960b72d995e9874b6f427a2d84a3dab31402d2da3298a66329b07382f97620ba7e0782212e4be3316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
